# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('claimedby', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('awoiaf_url', models.URLField()),
            ],
        ),
    ]
