# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Atlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('awoiaf_url', models.URLField()),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atlas.Kingdoms')),
            ],
        ),
    ]
